apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: hello-kairos
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: KairosCluster
    name: hello-kairos
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: KairosCluster
metadata:
  name: hello-kairos
spec:
  cloudConfig: |
     foo baz bar
  options:
    foo: bar